### Importing numpy library

---



In [16]:
import numpy as np

### Build Support Vector Machine Classifier

---



In [22]:
from threading import Condition
class SVM_classifier():

  def __init__(self, learning_rate, no_of_iteration, lambda_parameter):
    self.learning_rate = learning_rate
    self.no_of_iteration = no_of_iteration
    self.lambda_parameter = lambda_parameter

  def fit(self, X, Y):
    self.m, self.n = X.shape

    self.w = np.zeros(self.n)
    self.b = 0
    self.X = X
    self.Y = Y

    for i in range(self.no_of_iteration):
      self.update_weights()

  def update_weights(self):
    y_label = np.where(self.Y <= 0, -1, 1)

    for index, x_i in enumerate(self.X):
      Condition = y_label[index] * (np.dot(x_i, self.w) - self.b) >=1

      if (Condition == True):
        dw = 2 * self.lambda_parameter * self.w
        db = 0

      else:
        dw = 2 * self.lambda_parameter * self.w - np.dot(x_i, y_label[index])
        db = y_label[index]

      self.w = self.w - self.learning_rate * dw
      self.b = self.b - self.learning_rate * db

  def predict(self, X):
    output = np.dot(X, self.w) - self.b
    predicted_labels = np.sign(output)
    y_hat = np.where(predicted_labels <= -1, 0, 1)

    return y_hat

### Importing the Dependencies

---



In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


---

### Data Collection and Pre-*Processing*

In [3]:
# loading the data from csv file to pandas DataFrame
diabetes_data = pd.read_csv('/content/diabetes.csv')

In [4]:
# print the first 5 rows of the dataframe
diabetes_data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
diabetes_data['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [6]:
# separating the features and target
features = diabetes_data.drop(columns = 'Outcome', axis=1)
target = diabetes_data['Outcome']

In [7]:
features

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [8]:
target

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

### Data Standardization

---



In [9]:
scaler = StandardScaler()

In [10]:
scaler.fit(features)

StandardScaler()

In [11]:
Standardized_data = scaler.transform(features)

In [12]:
Standardized_data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [13]:
features = Standardized_data
target = diabetes_data['Outcome']

### Train Test Split

---



In [14]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=2)

In [24]:
features.shape, X_train.shape, X_test.shape

((768, 8), (614, 8), (154, 8))

### Train the Model

---



In [25]:
svm_classifier = SVM_classifier(learning_rate=0.001, no_of_iteration=1000, lambda_parameter=0.01)

In [27]:
# training the svm classifier with training data
svm_classifier.fit(X_train, y_train)

### Model Evaluation

---



Accuracy Score

In [28]:
# accuracy score on training data
X_train_prediction = svm_classifier.predict(X_train)

In [29]:
training_data_accuracy = accuracy_score(y_train, X_train_prediction)

In [30]:
training_data_accuracy

0.7768729641693811

In [31]:
# accuracy score on testing data
X_test_prediction = svm_classifier.predict(X_test)

In [32]:
test_data_accuracy = accuracy_score(y_test, X_test_prediction)

In [33]:
test_data_accuracy

0.7532467532467533

### Building a Predictive System

---



In [34]:

# Input data
input_data = (5, 166, 72, 19, 175, 25.8, 0.587, 51)

In [35]:
# Create a DataFrame with column names
input_data_df = pd.DataFrame([input_data], columns=diabetes_data.columns.drop('Outcome'))

In [36]:
# Display the DataFrame
input_data_df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            5      166             72             19      175  25.8   

   DiabetesPedigreeFunction  Age  
0                     0.587   51

In [37]:
# standardized the data
std_data = scaler.transform(input_data_df)

In [38]:
std_data

array([[ 0.3429808 ,  1.41167241,  0.14964075, -0.09637905,  0.82661621,
        -0.78595734,  0.34768723,  1.51108316]])

In [39]:
# predict the outcome
prediction = svm_classifier.predict(std_data)

In [40]:
prediction

array([1])

In [42]:
# Output the result
if prediction[0] == 0:
    print('The person is not diabetic')
else:
    print('The Person is diabetic')


The Person is diabetic


In [43]:
print(confusion_matrix(y_test, X_test_prediction))

[[96 13]
 [25 20]]


In [44]:
print(classification_report(y_test, X_test_prediction))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83       109
           1       0.61      0.44      0.51        45

    accuracy                           0.75       154
   macro avg       0.70      0.66      0.67       154
weighted avg       0.74      0.75      0.74       154

